### ISSUE TITLE
ros2 foxy problem with launching urdf_tutorial 

### ISSUE THREAD

**Issue by p4lik4ri** [ros/urdf_tutorial#55]
i am trying to launch the py file inside the launch folder but i get this error how do i fix this?
![Screenshot from 2021-11-22 19-33-40](https://user-images.githubusercontent.com/94470659/142908366-c309990b-fae1-4ac1-b664-581693c13560.png)

**Comment by kokerf** [comment]
hello @p4lik4ri , I have the same problem! Have you already fixed it?

**Comment by p4lik4ri** [comment]
hello @kokerf no i am still struggling to find a solution but nothing...but if i find one i will let you know hope you do the same

**Comment by p4lik4ri** [comment]
can someone please help i am stack here i am new to ros2 and i would really appreciate some help

**Comment by ilVecc** [comment]
I had this issue too, it seems like the script is passing a Path from pathlib instead of a simple string. Simply replace the default parameters in the `display.launch.py` file to
`default_model_path = str(urdf_tutorial_path / 'urdf/01-myfirst.urdf')`
`default_rviz_config_path = str(urdf_tutorial_path / 'rviz/urdf.rviz')`
and rebuild your colcon workspace (and resource it of course :) )

In my case, this new issue emerged:
`FileNotFoundError: [Errno 2] No such file or directory: 'xacro'`
but I solved it simply by running
`sudo apt install ros-foxy-xacro`

Now everything works like a charm.

**Comment by p4lik4ri** [comment]
> 
hello @ilVecc i did everything you adviced but i have the same error as previously nothing changed (i did the colcon build command ,sourced it ,installed xacro but nothing :(

**Comment by p4lik4ri** [comment]
i did everything above but i have the same error for some reason :(


Στις Πέμ, 25 Νοε 2021 στις 1:32 π.μ., ο/η Sebastiano Fregnan <
***@***.***> έγραψε:

**Comment by clalancette** [comment]
This is fixed by #53, so closing.
