### ISSUE TITLE
How to install urdf_tutorial binaries for ros2 foxy

### ISSUE THREAD

**Issue by kevinshao7** [ros/urdf_tutorial#59]
My problem is simple. I can't seem to install the urdf-tutorial ros2 foxy binaries. Am I missing something obvious?

Input:
sudo apt install ros-foxy-urdf-tutorial

Output:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-foxy-urdf-tutorial

**Comment by kevinshao7** [comment]
I checked the [status page](http://repo.ros2.org/status_page/foxy_default.html?q=urdf) of the ros2 repos and it shows that urdf-tutorial is missing. Is there way around this? Should I build the package myself?

**Comment by clalancette** [comment]
> I checked the [status page](http://repo.ros2.org/status_page/foxy_default.html?q=urdf) of the ros2 repos and it shows that urdf-tutorial is missing. Is there way around this? Should I build the package myself?

That's right.  What that status means is that the package has been released, but we haven't done a Foxy sync with it available.  That means that the package should be available in the near future (probably in the next couple of weeks).

If you don't want to wait for it to become broadly available, you have two options:
1.  You can use the "testing" repository to get the packages.  This is all of the latest packages that are available, as soon as they successfully build.  These are essentially the pre-release binaries that are going to make it into the next release.  If you want to enable this repository, then change `https://packages.ros.org/ros2/ubuntu` to `https://packages.ros.org/ros2-testing/ubuntu` in `/etc/apt/sources.list.d/ros2.list`
2. Build the package from source yourself.  You can do this by [making a workspace](https://docs.ros.org/en/foxy/Tutorials/Workspace/Creating-A-Workspace.html) and cloning this repository into that workspace.

Since this is a question more than an issue, I'm going to close this out.
